pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*
pkill memcached || taskkill -f -im memcached*
pkill python || taskkill -f -im python*
pkill mintty || taskkill -f -im mintty*
pkill bash || taskkill -f -im bash*